name = "MillerIndices"
uuid = "f41335bc-9121-4844-b5af-1d5721981e9a"
authors = ["singularitti <singularitti@outlook.com> and contributors"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
CrystallographyBase = "93b1d1cd-a8ea-4aa5-adb1-b2407ea0ba8d"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Combinatorics = "0.7, 1"
StaticArrays = "0.8.3, 0.9, 0.10, 0.11, 0.12, 1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
